### PR TITLE
Tuenc

### PR DESCRIPTION
**Pull request by josephwright**
Update to work with kernel changes

### CODE REVIEW

**Comment by wspr** [comment]
thanks… now just need to update mathspec.sty (have permission from the author) before releasing… 

Oh.
Maybe it would make more sense for backwards compatibility to have `\usepackage[EUx,TU]{fontenc}` — at least then older packages that explicitly reference EUx won't break quite so hard.

**Comment by wspr** [comment]
I'd need to test but that might allow me to release sooner rather than later.

**Comment by josephwright** [comment]
@wspr  The broader plan was to release `fontspec` along with the kernel at the turn of the year, and to ask CTAN to install the two together.

**Comment by wspr** [comment]
Do they need to be synchronised? I’d rather have some redundant code in fontspec for a little while than risk breaking things.

**Comment by josephwright** [comment]
@wspr  The plan is to move the TU encoding files from `fontspec` to the kernel. If we don't do that in sync we end up with two copies in the TeX tree or (worse) no copy at all!

**Pull request merged**
